Refactor structure and parts interactions
blackbeltlabs/Annotations pull request #33
Opened 2022-10-22 17:28 UTC by ulian-onua

@memstel this PR contains refactored version of Annotations framework.

The key concepts are:

- The new approach separates logic and rendering. The rendering is mostly generic, based on layers, styles and views. DrawableView doesn’t know anything about exact models;

- The models structure in Models Managers is homogenous with the usage of protocol AnnotationModels. The actions under models (move, resize, change color etc) are performed through common methods and applicable to any model. In the previous version, there were multiple arrays that contained models of each type (pens, highlights, rects etc) that complicated things and contained duplicated methods because of that;

- All math calculations are performed on a logic level based on actual annotation models. Mouse touch events are redirected to the logic level and processed there depending on model coordinates data (depending if there is an annotation model under mouse press, knobs positions if need to move an annotation or drag knob etc);

- Based on Combine streams renderer updates rendering on canvas each time the models' data structure is updated. It is not just a blind update of all models but a smarter one that can be used for some specific cases (for example, when a user edits text annotation only some UI parts of it should be updated);

- The new approach to the History of performed actions that are based on the wrapper of the system’s NSUndoManager and closures. The new history manager is returned by the framework. History is managed by the Annotations framework now but returned as a public instance. Now the history of the annotation canvas can be combined with other actions inside the app that uses it (for example, on Zappy pinned window). It is possible to add multiple actions to a single History event and undo / redo it later;

- No more bunch of delegate callbacks that must have been implemented as empty methods but weren’t used anymore. Now with Combine flow things are more lightweight and easier;

- Text Annotations are completely integrated with the new flow. Before that, it was inside a separate framework for some time and then was added through adapters. It required some duplications to use text annotations together with other annotations. Now text annotations are just a type of annotation model and all common approaches are applied to it. It made it possible to reduce a lot of code;

- A new approach made it possible to reduce a lot of code. The same flow is used for rendering any type of annotations which makes it easier to debug and improve; 

- A new JSON serialisation / deserialisation approach.

https://user-images.githubusercontent.com/15073398/197354059-4ef209be-ef16-4653-bcff-94575aa0e805.mp4

![image](https://user-images.githubusercontent.com/15073398/197354070-5b53fac8-7054-4e8f-bff0-50c2fe68f7b4.png)

2022-10-25 12:11 UTC, memstel requested changes

2022-10-25 12:11 UTC, memstel commented on Example/Annotations/Playground Controller/PlaygroundViewController.swift
> +      return "Can't create url from bundle from \(name).\(ext)"
move static texts to localizable files

2022-10-25 12:11 UTC, memstel commented on Example/Annotations/Views/CanvasControlsView.swift
> +}
move static texts to localizable files

2022-10-25 12:11 UTC, memstel commented on Sources/Annotations/Classes/Managers/Analytics.swift
> +    }
move static texts to localizable files

2022-10-25 17:17 UTC, ulian-onua commented on Example/Annotations/Views/CanvasControlsView.swift
> +}
@memstel these strings are in the Example project so I don't think it is something that needs to be localized.

2022-10-25 17:18 UTC, ulian-onua commented on Example/Annotations/Playground Controller/PlaygroundViewController.swift
> +      return "Can't create url from bundle from \(name).\(ext)"
@memstel these strings are in the Example project so I don't think it is something that needs to be localized.

2022-10-25 17:35 UTC, ulian-onua commented on Sources/Annotations/Classes/Managers/Analytics.swift
> +    }
@memstel done. Moved to Localizable.strings of Package.

2022-10-27 06:54 UTC, memstel approved these changes

2022-10-27 06:55 UTC, merged